###
### Ansible NAS Features
###
# Set these options to true or false to toggle specific features

# BitTorrent
# If you plan to use Transmission with OpenVPN, you'll need to copy group_vars/vpn_credentials.yml.dist
# to group_vars/vpn_credentials.yml, then update it with your own settings.
# transmission_with_openvpn_enabled: false
# transmission_enabled: false

# Plex
plex_enabled: false
tautulli_enabled: false


# Media Sourcing
# sonarr_enabled: false
# sickrage_enabled: false
# couchpotato_enabled: false
# radarr_enabled: false

# System Management
portainer_enabled: true
glances_enabled: true
stats_enabled: false

# Backup & Restore
# duplicati_enabled: true
# nextcloud_enabled: false
# nginx_enabled: true # if you enable nginx, you'll need to map ports 80 and 443 on your router to your Ansible-NAS

# IRC bouncer
# znc_enabled: false



###
### General
###
# Sets the hostname of your Ansible NAS
ansible_nas_hostname: skylab

# set some important info for later...
nas_host_ip: 192.168.0.208
nas_timezone: America/Denver

# Update all apt packages when playbook is run
# we will use Yum, but this can stay
keep_packages_updated: false

# Will be added to the docker group to give user command line access to docker
ansible_nas_user: jlegbandt

# Your email address, used for LetsEncrypt SSL certs
ansible_nas_email: jlegbandt@gmail.com

###
### RH-Base Config items
###
#rhbase_enable_repos:

rhbase_install_packages:
  - epel-release
  - smartmontools
  - htop
  - bonnie++
  - unzip
  - lm_sensors
  - avahi

rhbase_override_firewalld_zones: true
rhbase_firewall_interfaces: eno1

rhbase_firewall_allow_services:
  - samba
  - mdns


###
### Docker
###
# Where you want Docker to store its images and container data.
docker_home: /mnt/skylab_volumes/containers

# Docker storage driver, see https://docs.docker.com/storage/storagedriver/select-storage-driver/#supported-backing-filesystems
# You'll need to change this if your docker_home isn't on zfs and Docker won't start (you'll probably want overlay2 instead)
docker_storage_driver: overlay2

###
### Samba
###
# The location where all shares will be created by default. Can be overridden on a per-share basis.
# This path will be mounted to backup containers, Duplicati
samba_server_string: Samba on %m
samba_workgroup: WORKGROUP
samba_shares_root: /mnt/skylab_volumes/samba
samba_server_min_protocol: SMB3_11
samba_domain_master: true
samba_local_master: true
samba_apple_extensions: yes

# Where stuff downloaded will be stored
downloads_root: "{{ samba_shares_root }}/downloads"

# Where your movies are stored
movies_root: "{{ samba_shares_root }}/movies"

# Where your TV episodes are stored
tv_root: "{{ samba_shares_root }}/tv"

# Where torrent files are stored (picked up by Transmission for downloading)
torrents_root: "{{ samba_shares_root }}/torrents"

# The account used when Samba shares are accessed. Shouldn't need to change this unless you want to
# mess with Samba user permissions.
samba_guest_account: nobody

samba_users:
  - name: jlegbandt
  - password: replacewithplaintextpassword
# Shares you want published over Samba.
samba_shares:
  - name: downloads
    comment: 'Stuff downloaded'
    guest_ok: yes
    public: yes
    writable: yes
    path: "{{ downloads_root }}"

  - name: movies
    comment: 'Movies'
    guest_ok: yes
    public: yes
    writable: yes
    path: "{{ movies_root }}"

  - name: tv
    comment: 'TV Episodes'
    guest_ok: yes
    public: yes
    writable: yes
    path: "{{ tv_root }}"

  - name: public
    comment: 'public'
    guest_ok: yes
    public: yes
    writable: yes
    path: "{{ samba_shares_root }}/public"

  - name: photos
    comment: 'Pictures'
    guest_ok: yes
    public: yes
    writable: yes
    path: "{{ samba_shares_root }}/photos"

###
### Nextcloud
###

# Used by the nginx container to determine what hostname to retrieve an SSL cert for
# Ensure that this DNS name is registered and points to your external IP address
nextcloud_external_hostname: external.hostname.com

##################################################################
###### You shouldn't need to edit anything below this point ######
##################################################################

###
### Transmission
###
transmission_config_directory: "{{ docker_home }}/transmission/config"
transmission_download_directory: "{{ downloads_root }}"
transmission_watch_directory: "{{ torrents_root }}"
transmission_user_id: 0
transmission_group_id: 0
transmission_local_network: "192.168.1.0/24"


###
### Plex
###
plex_config_directory: "{{ docker_home }}/plex/config"
plex_movies_directory: "{{ movies_root }}"
plex_tv_directory: "{{ tv_root }}"
plex_user_id: 0
plex_group_id: 0


###
### Tautulli
###
tautulli_config_directory: "{{ docker_home }}/tautulli/config"
tautulli_user_id: 0
tautulli_group_id: 0


###
### Duplicati
###
duplicati_data_directory: "{{ docker_home }}/duplicati/config"


###
### Sonarr
###
sonarr_data_directory: "{{ docker_home }}/sonarr/config"
sonarr_tv_directory: "{{ tv_root }}"
sonarr_download_directory: "{{ downloads_root }}"
sonarr_user_id: 0
sonarr_group_id: 0


###
### Radarr
###
radarr_movies_directory: "{{ movies_root }}"
radarr_download_directory: "{{ downloads_root }}"
radarr_data_directory: "{{ docker_home }}/radarr"
radarr_user_id: 0
radarr_group_id: 0


###
### Couchpotato
###
couchpotato_config_directory: "{{ docker_home }}/couchpotato/config"
couchpotato_movies_directory: "{{ movies_root }}"
couchpotato_downloads_directory: "{{ downloads_root }}"
couchpotato_torrents_directory: "{{ torrents_root }}"
couchpotato_user_id: 0
couchpotato_group_id: 0


###
### Sickrage
###
sickrage_config_directory: "{{ docker_home }}/sickrage/config"
sickrage_tv_directory: "{{ tv_root }}"
sickrage_downloads_directory: "{{ downloads_root }}"
sickrage_user_id: 0
sickrage_group_id: 0


###
### OpenVPN
###
openvpn_config_directory: "{{ docker_home }}/openvpn"


###
### Portainer
###
portainer_data_directory: "{{ docker_home }}/portainer/config"


###
### ZNC
###
znc_data_directory: "{{ docker_home }}/znc"
znc_user_id: 0
znc_group_id: 0


###
### Stats
###
telegraf_data_directory: "{{ docker_home }}/telegraf"
influxdb_data_directory: "{{ docker_home }}/influxdb"
grafana_data_directory: "{{ docker_home }}/grafana"
stat_collection_interval: 15s

###
### Nextcloud
###
nextcloud_data_directory: "{{ docker_home }}/nextcloud"

###
### nginx
###
nginx_data_directory: "{{ docker_home }}/nginx"
